name: Actions 😎

on: [push, pull_request]

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  testAllModes:
    name: Test in ${{ matrix.testMode }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testMode:
          - All
    steps:
      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/cache@v3
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-node20 # Adjusted cache key for Node.js 20
          restore-keys: |
            Library-${{ matrix.projectPath }}-node20 # Adjusted restore key for Node.js 20

      - uses: game-ci/unity-test-runner@v4
        id: tests
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          testMode: ${{ matrix.testMode }}
          # githubToken: ${{ secrets.GITHUB_TOKEN }}
